language: php
os: linux
dist: xenial
services:
  - mysql
php:
  - 7.3
env:
  COMPOSER_HOME=$HOME/.config/composer

cache:
  directories:
     - $COMPOSER_HOME/cache
     - $HOME/.drush/cache

install:
  - export PATH="$COMPOSER_HOME/vendor/bin:$PATH"
  - composer global require drush/drush:8.1.* phpunit/phpunit:6.4.* torotil/upal:1.2.0

before_script:
  - repo=`pwd`
  - root=$HOME/test-root
  - mysql -e 'create database drupal'
  - php -d include_path=`pwd` -d sendmail_path=`which true` $COMPOSER_HOME/vendor/bin/drush.php --yes core-quick-drupal --core=drupal-7.69 --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/drupal --root=$root
  - ln -s $repo $root/sites/all/modules/module_under_test
  - cd $root
  - drush --yes pm-enable theming

script:
  - cd $repo
  - UPAL_ROOT=$root UPAL_WEB_URL=http://127.0.0.1 phpunit --bootstrap=$COMPOSER_HOME/vendor/torotil/upal/bootstrap.php --coverage-clover=coverage.xml .

after_success:
  - bash <(curl -s https://codecov.io/bash)
