<?php

/**
 * @file
 * Hook implementations for the theming module.
 */

/**
 * Implements hook_theme_registry_alter().
 */
function theming_theme_registry_alter(&$hooks) {
  $path = drupal_get_path('module', 'theming');
  $file = 'theming.theme.inc';
  $override = [
    'form_element',
    'form_element_label',
  ];
  foreach ($override as $name) {
    $hook = &$hooks[$name];
    $hook['theme path'] = $path;
    $hook['file'] = $file;
    $hook['includes'][] = "$path/$file";
    $hook['function'] = "theming_$name";
    // Depending on whether theming.theme.inc was included already the
    // prepocess function might have been detected automatically.
    // Make sure it’s added exactly once.
    $hook['preprocess functions'][] = "theming_preprocess_$name";
    $hook['preprocess functions'] = array_unique($hook['preprocess functions']);
  }
}
